steps:
  - name: 'docker/compose:1.24.0'
    args: ['-f', 'production.yml','up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'surfscribe_backend:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
