steps:
  - name: 'dutchandbold/laravel-docker'
    id: 'install composer deps'
    args: ['composer', 'install', '--no-dev', '--optimize-autoloader', '--no-interaction', '--no-scripts']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build docker image'
    args: ['build', '-t', 'gcr.io/surfscribe/github.com/ian-starts/surfscribe-backend:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push docker image'
    args: ['push', 'gcr.io/surfscribe/github.com/ian-starts/surfscribe-backend:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create new template'
    args: ['compute','instance-templates', 'create-with-container', 'surfscribe-backend-$COMMIT_SHA',
           '--container-image', 'gcr.io/surfscribe/github.com/ian-starts/surfscribe-backend:$COMMIT_SHA',
            '--machine-type=f1-micro']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'execute rolling update'
    args: ['compute', 'instance-groups', 'managed', 'rolling-action', 'start-update' , 'surfscribe-instance-group', '--version', 'template=surfscribe-backend-$COMMIT_SHA', '--zone', 'us-east1-b']
