steps:
  - name: 'docker/compose:latest'
    args: ['-f', 'production.yml','up', '-d', 'db', 'cache']
  - name: 'docker/compose:latest'
    args: ['tag', 'surfscribe_backend:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
