apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: 2019-04-12T13:48:44Z
  generation: 9
  labels:
    run: surfscribe-pod
  name: surfscribe-pod
  namespace: default
  resourceVersion: "131154"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/surfscribe-pod
  uid: b09f06da-5d29-11e9-8f0e-42010a84000f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: surfscribe-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: surfscribe-pod
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: dbname
              name: cloudsql-db-credentials
        image: gcr.io/surfscribe/github.com/ian-starts/surfscribe-backend:a3944988479b44a6f1ad35c72b1562e31b45356f
        imagePullPolicy: IfNotPresent
        name: surfscribe-pod
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=surfscribe:europe-west1:surfscribe=tcp:3306
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: surfscribe-secrets-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: surfscribe-secrets-volume
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-04-12T13:49:21Z
    lastUpdateTime: 2019-04-12T13:49:21Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-04-12T13:48:44Z
    lastUpdateTime: 2019-04-13T04:10:25Z
    message: ReplicaSet "surfscribe-pod-68f5ccb966" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
