apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2019-05-09T12:34:48Z
  generation: 2
  labels:
    app: surfscribe-deployment
  name: surfscribe-deployment
  namespace: default
  resourceVersion: "2602"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/surfscribe-deployment
  uid: d54416b3-7256-11e9-b481-42010a800039
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: surfscribe-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: surfscribe-deployment
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: dbname
              name: cloudsql-db-credentials
        image: gcr.io/surfscribe/github.com/ian-starts/surfscribe-backend@sha256:6d5e2d2403ed2437471ae2f2e2600efba1139b47eb97066d6074c7f0643ddb36
        imagePullPolicy: IfNotPresent
        name: surfscribe-backend-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=surfscribe:europe-west1:surfscribe=tcp:3306
        - -credential_file=/secrets/cloudsql/credentials.json
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: surfscribe-secrets-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: surfscribe-secrets-volume
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
status:
  conditions:
  - lastTransitionTime: 2019-05-09T12:37:25Z
    lastUpdateTime: 2019-05-09T12:37:25Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 4
  unavailableReplicas: 4
  updatedReplicas: 2
